<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRM.CCaaS.IVR.GRammarImportTool.ServiceDefaults\CRM.CCaaS.IVR.GRammarImportTool.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
