<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateRuntimeConfigDevFile>true</GenerateRuntimeConfigDevFile>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />    
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.AI.Evaluation" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRM.CCaaS.IVR.GRammarImportTool.ApiService\CRM.CCaaS.IVR.GRammarImportTool.ApiService.csproj" />
    <ProjectReference Include="..\CRM.CCaaS.IVR.GRammarImportTool.Stubs\CRM.CCaaS.IVR.GRammarImportTool.Stubs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\grit-test-data-1.grxml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\grit-test-data-1.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\grit-test-data-2.grxml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\grit-test-data-2.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\grit-test-data-3.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <TestDataFiles Include="$(RepoRoot)\$(MSBuildProjectName)\Data\grit-test-data-1.zip;$(RepoRoot)\$(MSBuildProjectName)\Data\grit-test-data-2.zip;$(RepoRoot)\$(MSBuildProjectName)\Data\grit-test-data-3.zip" />
  </ItemGroup>

  <Target Name="CreateDirectories" AfterTargets="Build">
      <MakeDir Directories="$(OutputPath)\Data" />    
  </Target>
  <Target Name="CopyFiles" AfterTargets="Build">
    <Message Text="Copy Data Files CRM.CCaaS.IVR.GRammarImportTool.Tests.L1" Importance="high" />
      <Copy SourceFiles="@(TestDataFiles)" DestinationFolder="$(OutputPath)\Data" />
  </Target>

  <ItemGroup>
    <_CustomFilesToDelete Include="$(OutputPath)" />
  </ItemGroup>
  <Target Name="CustomClean" AfterTargets="Clean">
    <Message Text="Clean CRM.CCaaS.IVR.GRammarImportTool.Tests.L1" Importance="high" />
    <RemoveDir Directories="@(_CustomFilesToDelete)" />
  </Target>
</Project>