<Project>
    <Target Name="CustomClean" BeforeTargets="Clean">
      <Message Text="Clean CRM.CCaaS.IVR.GRammarImportTool.AppHost" Importance="high"/>
        <ItemGroup>
         <_CustomFilesToDelete Include="$(RepoRoot)\out\CRM.CCaaS.IVR.GRammarImportTool.AppHost"/>
        </ItemGroup>
        <RemoveDir Directories='@(_CustomFilesToDelete)'/>
        <!--<RemoveDir Directories="$(RepoRoot)\out" />-->
    </Target>
</Project>
