#################################################################################
#                               OneBranch Pipelines                             #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: # https://aka.ms/obpipelines/triggers
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - '**/*.md'

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/*.md'

# global parameteres are configured here and show up in AzDO UI in build queue time. Required for MSBuild and .NET.
# learn more at https://aka.ms/obpipelines/parameters
parameters:
  - name: 'debug'
    displayName: 'Enable debug output'
    type: boolean
    default: false

variables:
  - template: ./variables.yml

  - name: BuildTemplate
    value: pr

  ### Specify other global variables in this section! ###
  # https://aka.ms/obpipelines/variables

resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates  # https://aka.ms/obpipelines/templates
  parameters:
    featureFlags:
      LinuxHostVersion:
        Network: R1
      WindowsHostVersion:
        Version: 2022
        Network: R1
    cloudvault:  # https://aka.ms/obpipelines/cloudvault
      enabled: false
      ### Linux Pipelines can uncomment the following to run CloudVault update as a seperate stage. ###
      # runmode: stage
      # dependsOn: linux_build
      # artifacts:
      #  - drop_linux_stage_linux_job
    globalSdl:  # https://aka.ms/obpipelines/sdl
      tsa:
        enabled: false  # onebranch publish all SDL results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      # credscan:
        # suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      binskim:
        break: true  # always break the build on binskim issues in addition to TSA upload
      policheck:
        break: true  # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress

    stages:
    # The file contains an example HelloWorld script. For more info and examples, see the links below
    # https://aka.ms/obpipelines/containerbuildexamples
    # https://aka.ms/obpipelines/containerprojectypes
    - stage: build
      displayName: Build
      jobs:
      - job: main
        pool:
          type: windows  # "linux" can be used if performing a linux-based container build
        variables:
          ob_outputDirectory: '$(Build.SourcesDirectory)\out'  # this directory is uploaded to pipeline artifacts and cloudvault. More info at https://aka.ms/obpipelines/artifacts
          ob_sdl_binskim_break: true # https://aka.ms/obpipelines/sdl
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}: # conditionally enable symbolsPublishing for master branch only
            ob_symbolsPublishing_enabled: true # https://aka.ms/obpipelines/symbols
          
          # ob_sdl_suppression_suppressionFile: $(Build.SourcesDirectory)\.gdn\build.official.gdnsuppress
        steps:
        - template: .pipelines/templates/pre-build-steps.yml@self
        - template: .pipelines/templates/build-steps.yml@self
        - template: .pipelines/templates/post-build-steps.yml@self

